### ISSUE TITLE
Website Link in about section not Working

### ISSUE THREAD

**Issue by Amandeep404** [arpit456jain/Getting-Started-with-open-source#136]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- The website link in the about section is not working 

## **Possible solution**

- Update the website link to the correct one 

## **Screenshots**
![image](https://user-images.githubusercontent.com/107784525/195639091-6b7086b7-cfea-49bb-a0cb-6be66e3c2572.png)

 ![image](https://user-images.githubusercontent.com/107784525/195638805-454a0695-2e08-4043-99c2-89c777ef3223.png)

**Comment by Sodium-Sharma** [comment]
hey @Amandeep404 , i would like to help you with this issue, Assign this to me.

**Comment by amardeep911** [comment]
Plz assigned this to me @Amandeep404

**Comment by Amandeep404** [comment]
@arpit456jain look towards this issue

**Comment by arpit456jain** [comment]
done
